package recomovie.userservice.constants;

public interface ErrorConstants {

    String EMAIL_ALREADY_CONFIRMED = "EMAIL_ALREADY_CONFIRMED";
    String EMAIL_CONFIRMED_SUCCESS = "EMAIL_CONFIRMED_SUCCESS";
    String EMAIL_FAIL_TO_SEND = "EMAIL_FAIL_TO_SEND";
    String EMAIL_FORMAT_NOT_VALID = "EMAIL_FORMAT_NOT_VALID";
    String TOKEN_EXPIRED = "TOKEN_EXPIRED";
    String TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND";
    String USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS";
    String USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND";
    String LOGIN_INVALID_CREDENTIALS = "LOGIN_INVALID_CREDENTIALS";
    String ACCOUNT_NOT_CONFIRMED = "ACCOUNT_NOT_CONFIRMED";
    String USER_NOT_FOUND = "USER_NOT_FOUND";

}
